# Full credit to - https://gcits.com/knowledge-base/warn-users-external-email-arrives-display-name-someone-organisation/
# Modified to just drop the message silently rather than prefixing a warning to it as the original script above does
# Needs to be run each time users are added or removed from tenancy; $displayNames are generated by this script. 
# See link above for options to automate

$ruleName = "Delete e-mails from External Senders with matching display names"
 
Connect-ExchangeOnline
 
$rule = Get-TransportRule | Where-Object {$_.Identity -contains $ruleName}
$displayNames = (Get-Mailbox -ResultSize Unlimited).DisplayName
 
if (!$rule) {
    Write-Host "Rule not found, creating rule" -ForegroundColor Green
    New-TransportRule -Name $ruleName -Priority 0 -FromScope "NotInOrganization" -HeaderMatchesMessageHeader From -HeaderMatchesPatterns $displayNames -DeleteMessage $true
}
else {
    Write-Host "Rule found, updating rule" -ForegroundColor Green
    Set-TransportRule -Identity $ruleName -Priority 0 -FromScope "NotInOrganization" -HeaderMatchesMessageHeader From -HeaderMatchesPatterns $displayNames -DeleteMessage $true
}
